services:

  api1:
    build: ./api
    container_name: api1
    environment:
      INSTANCIA: API-1

  api2:
    build: ./api
    container_name: api2
    environment:
      INSTANCIA: API-2

  nginx:
    image: nginx:latest
    container_name: nginx-lb

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro

    depends_on:
      - api1
      - api2